### ISSUE TITLE
PowerShell 2.0 compatibility 

### ISSUE THREAD

**Issue by quattro004** [eavonius/powerdelivery#1]
This is more a question of compatibility than an issue. Are you going to support PowerShell 2.0? Apparently SharePoint 2010 has problems with 3.0. If not what are the reasons?

**Comment by jaymeedwards** [comment]
Hey there, sorry for the delay. No, I won't be supporting 2.0. The project
uses the String.IsNullOrWhitespace and a few other .NET framework APIs that
are not supported in that version.
